[package]
name = "emjudge-judgecore"
version = "0.1.0"
edition = "2021"

[lib]
name = "emjudge_judgecore"
path = "src/lib.rs"

[dependencies]
cgroups-rs = "0.3.4"
config = "0.13.4"
nix = {version = "0.27.1", features = ["process", "signal", "resource"]}
serde = "1.0.194"
serde_with = "3.4.0" 
toml = "0.8.8"
uuid = {version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"]}
