[languages.Octave]
exe_command = """
#!/bin/bash
ulimit -s unlimited
octave --no-gui --no-window-system main.m"""
exe_code = "main.m"

[languages.COBOL]
compile_command = """
#!/bin/bash
cobc -free -x main.cob -o main"""
raw_code = "main.cob"
exe_code = "main"
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""

[languages.Go]
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""
raw_code = "main.go"
compile_command = """
#!/bin/bash
go build -o main main.go"""
exe_code = "main"

[languages.Scala]
raw_code = "Main.scala"
compile_command = """
#!/bin/bash
scalac -d . Main.scala"""
exe_code0 = "Main.class"
exe_code1 = "Main$.class"
exe_command = """
#!/bin/bash
ulimit -s unlimited
scala -J-Xmx4g -J-Xss256m Main"""

[languages.Perl]
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main.pl"""
exe_code = "main.pl"

[languages.C]
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""
exe_code = "main"
compile_command = """
#!/bin/bash
gcc main.c -o main -O2 -lm -w -Wno-unused-result"""
raw_code = "main.c"

[languages.Javascript]
exe_command = "node main.js"
exe_code = "main.js"

[languages."Common LISP"]
exe_command = """
#!/bin/bash
ulimit -s unlimited
sbcl --script main.lisp"""
exe_code = "main.lisp"

[languages.Rust]
compile_command = """
#!/bin/bash
rustc main.rs -o main"""
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""
raw_code = "main.rs"
exe_code = "main"

[languages."Python 2"]
exe_command = """
#!/bin/bash
ulimit -s unlimited
python2 main.py2"""
exe_code = "main.py2"

[languages."Python 3"]
exe_command = """
#!/bin/bash
ulimit -s unlimited
python3 main.py3"""
exe_code = "main.py3"

[languages.PHP]
exe_code = "main.php"
exe_command = """
#!/bin/bash
ulimit -s unlimited
php main.php"""

[languages.Swift]
exe_code = "main"
raw_code = "main.swift"
compile_command = """
#!/bin/bash
swiftc main.swift -o main"""
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""

[languages.Kotlin]
exe_command = """
#!/bin/bash
ulimit -s unlimited
kotlin Main.jar"""
exe_code = "Main.jar"
raw_code = "Main.kt"
compile_command = """
#!/bin/bash
kotlinc Main.kt -include-runtime -d Main.jar"""

[languages."C++"]
raw_code = "main.cpp"
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""
exe_code = "main"
compile_command = """
#!/bin/bash
g++ main.cpp -o main -static -O2 -lm -w -Wno-unused-result -std=c++2a"""

[languages."C#"]
raw_code = "main.cs"
compile_command = """
#!/bin/bash
mcs -out:main main.cs"""
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""
exe_code = "main"

[languages.Julia]
exe_command = """
#!/bin/bash
ulimit -s unlimited
julia --startup-file=no main.jl"""
exe_code = "main.jl"

[languages.Ada]
compile_command = """
#!/bin/bash
gnatmake -o main main.adb"""
raw_code = "main.adb"
exe_code = "main"
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""

[languages.Ruby]
exe_command = """
#!/bin/bash
ulimit -s unlimited
ruby main.rb"""
exe_code = "main.rb"

[languages.Smalltalk]
exe_command = """
#!/bin/bash
ulimit -s unlimited
gst main.st"""
exe_code = "main.st"

[languages.Fortran]
exe_code = "main"
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""
compile_command = """
#!/bin/bash
gfortran -o main main.f90 -ffree-form"""
raw_code = "main.f90"

[languages.Objective-C]
compile_command = """
#!/bin/bash
gcc -I $(gnustep-config --variable=GNUSTEP_SYSTEM_HEADERS) -L $(gnustep-config --variable=GNUSTEP_SYSTEM_LIBRARIES) -o main main.m -lgnustep-base -fconstant-string-class=NSConstantString -D_NATIVE_OBJC_EXCEPTIONS -Wl,--no-as-needed -lgnustep-base -lobjc"""
raw_code = "main.m"
exe_code = "main"
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""

[languages.Lua]
exe_command = """
#!/bin/bash
ulimit -s unlimited
lua main.lua"""
exe_code = "main.lua"

[languages.OCaml]
exe_code = "main"
raw_code = "main.ml"
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main"""
compile_command = """
#!/bin/bash
ocamlc main.ml -o main"""

[languages."Pypy 2"]
exe_code = "main.py2"
exe_command = """
#!/bin/bash
ulimit -s unlimited
pypy2 main.py2"""

[languages.Tcl]
exe_code = "main.tcl"
exe_command = """
#!/bin/bash
ulimit -s unlimited
./main.tcl"""

[languages.Java]
compile_command = """
#!/bin/bash
javac Main.java"""
exe_code = "Main.class"
raw_code = "Main.java"
exe_command = """
#!/bin/bash
ulimit -s unlimited
java -Xmx4g -Xss256m Main"""

[languages."Pypy 3"]
exe_command = """
#!/bin/bash
ulimit -s unlimited
pypy3 main.py3"""
exe_code = "main.py3"
