[languages."C++"]
compile_command = """
#!/bin/bash
g++ main.cpp -o main"""
exe_command = """
#!/bin/bash
ulimit -s unlimited
main"""
exe_file = "main"
raw_code = "main.cpp"

[languages.Python3]
exe_command = """
#!/bin/bash
ulimit -s unlimited
python3 main.py3"""
exe_file = "main.py3"
