[compile_setting.languages]
"C++" = ["g++", "cpp", "infile", "-o", "outfile", "-static", "-O2", "-lm", "-w", "-Wno-unused-result", "-std=c++2a"]
"C" = ["gcc", "c", "infile", "-o", "outfile", "-O2", "-lm", "-w", "-Wno-unused-result"]

[compile_setting]
dir = "compile"

[run_setting]
memory_limit_KB = 2097152
cpu_limit_ms = 10000 
dir = "run"
