[languages.COBOL]
exe_files = ["main"]
raw_code = "main.cob"
compile_command = """
cobc -free -x main.cob -o main"""
exe_command = """
./main"""

[languages.Scala]
exe_files = ["Main.class", "Main$.class"]
compile_command = """
scalac -d . Main.scala"""
exe_command = """
scala -J-Xmx4g -J-Xss256m Main"""
raw_code = "Main.scala"

[languages.Javascript]
exe_files = ["main.js"]
exe_command = "node main.js"

[languages.Go]
exe_files = ["main"]
raw_code = "main.go"
exe_command = """
./main"""
compile_command = """
go build -o main main.go"""

[languages.Swift]
exe_command = """
./main"""
exe_files = ["main"]
raw_code = "main.swift"
compile_command = """
swiftc main.swift -o main"""

[languages.Ruby]
exe_command = """
ruby main.rb"""
exe_files = ["main.rb"]

[languages.OCaml]
raw_code = "main.ml"
compile_command = """
ocamlc main.ml -o main"""
exe_files = ["main"]
exe_command = """
./main"""

[languages.Rust]
raw_code = "main.rs"
exe_files = ["main"]
exe_command = """
./main"""
compile_command = """
rustc main.rs -o main"""

[languages.Julia]
exe_command = """
julia --startup-file=no main.jl"""
exe_files = ["main.jl"]

[languages.Smalltalk]
exe_command = """
gst main.st"""
exe_files = ["main.st"]

[languages."C#"]
exe_command = """
./main"""
raw_code = "main.cs"
exe_files = ["main"]
compile_command = """
mcs -out:main main.cs"""

[languages.PHP]
exe_files = ["main.php"]
exe_command = """
php main.php"""

[languages.Java]
exe_files = ["Main.class"]
compile_command = """
javac Main.java"""
exe_command = """
java -Xmx4g -Xss256m Main"""
raw_code = "Main.java"

[languages."C++"]
exe_command = """./main"""
exe_files = ["main"]
compile_command = """
g++ main.cpp -o main -static -O2 -lm -w -Wno-unused-result -std=c++2a"""
raw_code = "main.cpp"

[languages.Tcl]
exe_files = ["main.tcl"]
exe_command = """
./main.tcl"""

[languages."Pypy 2"]
exe_command = """
pypy2 main.py2"""
exe_files = ["main.py2"]

[languages.Lua]
exe_files = ["main.lua"]
exe_command = """
lua main.lua"""

[languages."Common LISP"]
exe_files = ["main.lisp"]
exe_command = """
sbcl --script main.lisp"""

[languages.C]
compile_command = """
gcc main.c -o main -O2 -lm -w -Wno-unused-result"""
exe_command = """
./main"""
raw_code = "main.c"
exe_files = ["main"]

[languages."Python 2"]
exe_command = """
python2 main.py2"""
exe_files = ["main.py2"]

[languages.Octave]
exe_command = """
octave --no-gui --no-window-system main.m"""
exe_files = ["main.m"]

[languages."Python 3"]
exe_files = ["main.py3"]
exe_command = """
python3 main.py3"""

[languages.Fortran]
compile_command = """
gfortran -o main main.f90 -ffree-form"""
exe_files = ["main"]
exe_command = """
./main"""
raw_code = "main.f90"

[languages.Perl]
exe_command = """
./main.pl"""
exe_files = ["main.pl"]

[languages."Pypy 3"]
exe_files = ["main.py3"]
exe_command = """
pypy3 main.py3"""

[languages.Ada]
compile_command = """
gnatmake -o main main.adb"""
exe_files = ["main"]
raw_code = "main.adb"
exe_command = """
./main"""

[languages.Kotlin]
raw_code = "Main.kt"
exe_files = ["Main.jar"]
compile_command = """
kotlinc Main.kt -include-runtime -d Main.jar"""
exe_command = """
kotlin Main.jar"""
